services:
  db:
    image: postgres:15
    container_name: family_med_db
    environment:
      POSTGRES_DB: family_medicine_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password123
    ports:
      - "5432:5432"